name: ProFlow CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Verify Docker
      run: docker --version

    - name: Verify Docker Compose
      run: docker-compose --version

    - name: Build Containers
      run: docker-compose build

    - name: Run Containers
      run: docker-compose up -d

    - name: Show Running Containers
      run: docker ps